name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest tests/

      - name: Deploy to Google Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/$PROJECT_ID/toxic-comments-api
          gcloud run deploy toxic-comments-api --image gcr.io/$PROJECT_ID/toxic-comments-api --platform managed
